Fonctionnalités annexes
LionelDiot/Projet_Chaton pull request #38
Opened 2023-03-15 23:40 UTC by GGE95

Suppression photos dans le panier + Total € de la commande + redirection d'un user non identifié vers la page d'authentification après un clic sur Ajouter au panier (bancal : l'image ne se stocke pas dans le panier après authentification).

2023-03-15 23:50 UTC, soniapvg approved these changes
Je vois toujours le même soucis au niveau du fichier app/views/photos/_photo.html.erb
Mais tant pis, j'approuve quand même, ça pourra être modifié facilement après.

2023-03-16 00:02 UTC, GGE95 commented
> Je vois toujours le même soucis au niveau du fichier app/views/photos/_photo.html.erb Mais tant pis, j'approuve quand même, ça pourra être modifié facilement après.

Oui ! Je n'ai pas réussi à les enlever, même dans mon code VSC... c'est très bizarre

2023-03-16 01:48 UTC, LionelDiot requested changes
Beaucoup de details qui me gene c'est triste d'être en décalé ca se trouve je comprends la moitié des trucs à l'envers :(

2023-03-16 01:48 UTC, LionelDiot commented on app/controllers/application_controller.rb
N'ajoute le after_sign_in_path que si la fonctionnalité marche vu que ca redéfinit la methode de devise ? ( vu que l'ajout de pending photo dans session est commenté ca peut pas fonctionner ou j'ai mal compris ? ) de plus je vois pas l'interet d'utiliser un cart dans la session vu que la session est lié à la connection au site depuis un navigateur si je me trompe pas ? j'imagine que le code de chatgpt marchait pas non plus mais si c'est à fix laisse le sur la branche annexes et ne push pas sur development

2023-03-16 01:48 UTC, LionelDiot commented on app/controllers/photos_controller.rb
C'est sensé être dans le cart et son modèle comme le add_to_cart sur la meme base il faut un remove_from_cart qui marche similairement.

2023-03-16 01:48 UTC, LionelDiot commented on app/views/photos/_photo_row.html.erb
turbo_farme sert à connecté à une turbo frame qui aurait l'id photo et la faire apparaitre / la modifier remplacer par une frame d'une autre page ca n'a pas l'air d'être la bonne chose ici ?

2023-03-16 07:44 UTC, closed without merging