Organisation bdd
LionelDiot/Projet_Chaton pull request #4
Opened 2023-03-13 19:50 UTC by GGE95

2023-03-13 19:54 UTC, GGE95 commented
La seule modif significative par rapport à ce qu'on a fait ce matin - si je ne me trompe pas - tient au fait que la clé étrangère pour lier la table user et la table cart est stockée dans cette dernière. C'est à la fois plus logique (un user peut exister sans cart, l'inverse n'est pas vrai), et ca m'arrangeait pour l'ordre des migrations à passer (la table user était placée en 1ère position, sinon il aurait fallu changer le nom des tables, ce qui n'est pas forcément souhaitable).

2023-03-14 05:00 UTC, LionelDiot approved these changes
Ca m'a l'air  d'être une bonne base ! il manque tout de même les dependent destroy pour le cart et les selections et probablement d'autres petites choses.

2023-03-14 07:34 UTC, Jo9085 approved these changes
Yep good for me as well
- rajouter le nombre d'items dans Selections ? ("quantity" ou autre)
- je ne savais pas qu'on pouvait faire t.belongs_to dans les fichiers de migration mais tant mieux !!

2023-03-14 07:46 UTC, LionelDiot requested changes
Il faut changer de branche

2023-03-14 07:47 UTC, closed without merging